### ISSUE TITLE
Изменение производства

### ISSUE THREAD

**Issue by GoWebProd** [cobr123/cobr123.github.com#2]
Добавьте, пожалуйста, учёт имеющегося материала на складах, с которых ведётся расчёт.

**Comment by cobr123** [comment]
уже ведь есть поле "Объём доступного сырья"

**Comment by GoWebProd** [comment]
Но ведь разного сырья нужно разное кол-во, причём иногда во много раз

**Comment by cobr123** [comment]
как тогда указать отдельное количество для каждого материала?

**Comment by cobr123** [comment]
добавил отдельные поля для каждого ингредиента для ограничения объёма доступного сырья
